#!/bin/bash

# internal components
# EGFR,HGFR,ITG_AB,FAK_SRC,RAS,RAF1,MEK,ERK,PI3K,ILK,AKT,GSK3B,DVL,CK1,FAT4,LATS,NOTCH,YAP_TAZ,RPTP,RAP1,TGFBR,JAK,BCat,NFkB,SMAD,STAT3,JNK,HIF1a,PAK,CSL,TCF_LEF,SNAIL,SLUG,ZEB,miR200,ECad,ECad_AJ,BCat_AJ,p120_AJ

echo creating selvaggio_m1 problem and markers
biomarkers problem-create --problem selvaggio_problem.json --bnet selvaggio_emt --phenotype AJ_b1,AJ_b2,FA_b1,FA_b2,FA_b3
biomarkers problem-solve --problem selvaggio_problem.json --forbidden AJ_b1,AJ_b2,FA_b1,FA_b2,FA_b3 --marker-size-max 10 --markers selvaggio_markers.json

echo creating markers graph
biomarkers markers-graph --markers selvaggio_markers.json --graph selvaggio_markers_graph.pdf selvaggio_emt

echo creating markers control
biomarkers control-create --markers selvaggio_m1_markers.json
