#!/bin/bash

biomarkers problem-create --problem selvaggio_m1_problem.json --forbidden AJ_b1,AJ_b2,FA_b1,FA_b2,FA_b3 --bnet selvaggio_emt --phenotype AJ_b1=0,AJ_b2=0,FA_b1=1,FA_b2=0,FA_b3=0 --max-markers 3
biomarkers problem-solve --problem selvaggio_m1_problem.json
