#!/bin/bash

# internal components
# EGFR,HGFR,ITG_AB,FAK_SRC,RAS,RAF1,MEK,ERK,PI3K,ILK,AKT,GSK3B,DVL,CK1,FAT4,LATS,NOTCH,YAP_TAZ,RPTP,RAP1,TGFBR,JAK,BCat,NFkB,SMAD,STAT3,JNK,HIF1a,PAK,CSL,TCF_LEF,SNAIL,SLUG,ZEB,miR200,ECad,ECad_AJ,BCat_AJ,p120_AJ
# complement
#

AJ0="AJ_b1=0,AJ_b2=0"
AJ1="AJ_b1=1,AJ_b2=0"
AJ2="AJ_b1=1,AJ_b2=1"
FA0="FA_b1=0,FA_b2=0,FA_b3=0"
FA1="FA_b1=1,FA_b2=0,FA_b3=0"
FA2="FA_b1=1,FA_b2=1,FA_b3=0"
FA3="FA_b1=1,FA_b2=1,FA_b3=1"

M1=$AJ0,$FA1
M2=$AJ0,$FA2
M3=$AJ0,$FA3
H1=$AJ2,$FA1
H2=$AJ1,$FA2
H3=$AJ2,$FA3
E1=$AJ2,$FA0
UN=$AJ0,$FA0
M=$AJ0,"FA_b1=1"

FORBIDDEN="AJ_b1,AJ_b2,FA_b1,FA_b2,FA_b3"
MARKER_MAX=5

SUBSPACES=($M1 $M2 $M3 $H1 $H2 $H3 $E1 $UN $M)
NAMES=(m1 m2 m3 h1 h2 h3 e1 un m)

SUBSPACES=($H1 $H2 $H3 $E1 $UN $M)
NAMES=(h1 h2 h3 e1 un m)

echo_and_run() { echo "\$ $*" ; "$@" ; }

echo computing steady state correlation graph
echo_and_run biomarkers steady-states-correlation -p m_problem.json -g steady_state_correlation.pdf

for i in "${!SUBSPACES[@]}"; do
  echo computing ${NAMES[$i]} markers
  echo_and_run biomarkers problem-create --problem ${NAMES[$i]}_problem.json --bnet selvaggio_emt --phenotype ${SUBSPACES[$i]}
  echo_and_run biomarkers problem-solve --problem ${NAMES[$i]}_problem.json --forbidden $FORBIDDEN --marker-size-max $MARKER_MAX --markers ${NAMES[$i]}_markers.json
  echo_and_run biomarkers markers-graph --markers ${NAMES[$i]}_markers.json --graph ${NAMES[$i]}_markers_graph.pdf
  echo_and_run biomarkers control-create --markers ${NAMES[$i]}_markers.json --control ${NAMES[$i]}_control.json
  echo_and_run biomarkers control-export --control ${NAMES[$i]}_control.json --export ${NAMES[$i]}_control.tex --drop markers_names,red_states --green-only
  echo_and_run biomarkers markers-factorize --markers ${NAMES[$i]}_markers.json
done
